wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
total_run:
  desc: null
  value: 500
network:
  desc: null
  value: in->256->16->1
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1695800530.212489
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.17
      5: 0.15.11
      8:
      - 1
      - 2
      - 5
      13: darwin-arm64
